version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  sample:
    jobs:
    - build-and-test:
        docker:
          - image: circleci/node:14

        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
            name: Run tests
            command: npm test

workflows:
  sample: 
    jobs:
      - build-and-test