version: 2.1

orbs:
  python: circleci/python@2.1.1


jobs:
  build-and-test:
    docker:
      - image: circleci/node:14
          
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start server
          command: npm start &
      - run:
          name: Run tests
          command: |
            export SERVER_HOST=http://localhost:${PORT:-80}
            npm test
workflows:
  sample: 
    jobs:
      - build-and-test