version: 2.1

orbs:
  python: circleci/docker@1.0.0

jobs:
  build-and-test:
    docker:
      - image: rachelsjsu/cs218:latest
        auth:
          username: rachelsjsu
          password: dckr_pat_RsCzynytoHdYhdDvxvhT5TTaaQM
          
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests in Docker container
          command: |
            docker run rachelsjsu/cs218:latest npm test

workflows:
  sample:
    jobs:
      - build-and-test
