version: 2.1

orbs:
  python: circleci/docker@1.0.0
jobs:
  build-and-test:
    docker:
      - image: bikeimage:latest
        auth:
          username: rachelsjsu
          password: dckr_pat_RsCzynytoHdYhdDvxvhT5TTaaQM
          
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start server
          command: npm start &
      - run:
          name: Run tests
          command: 
            npm test
workflows:
  sample: 
    jobs:
      - build-and-test